### ISSUE TITLE
How to support UTF-8 Charsets

### ISSUE THREAD

**Issue by Yohn** [flrnull/php-pdo-chainer#3]
Hello again, not sure if you're still using this or not, but I am! haha and today I just stumbled upon a UTF8 issue where it was not returning information in UFT-8 format.

What I did to fix it, what in PDOChainer.php I added ;charset=utf8 after the dbname

    $db = new \PDO('mysql:host='.$host.';dbname='.$dbname.';charset=utf8', $user, $pass);

**Comment by flrnull** [comment]
Hi, I'm glad to hear it.
You could do Pull Request if you want. :)

**Comment by Yohn** [comment]
Actually it looks like you've added the option to do that in a newer version that I for some reason never downloaded. I've been using one of the first versions I guess from when I first found ya. The way you did it with `$db->exec("set names {$charset}");` should work fine!
